name: Build & Analyze with Microwalk

permissions:
  actions: read
  contents: read
  security-events: write

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  script_directory: microwalk

jobs:
  build-analyze:
    runs-on: ubuntu-latest
    steps:
      # If necessary, add step for building the library / downloading necessary packages
      # Alternatively, adapt the Makefile
      - uses: actions/checkout@v2
      
      - name: Run Microwalk analysis
        id: run_microwalk
        uses: microwalk-project/microwalk-pin-action@v1
        with:
          # Change this if the build/analysis scripts are not in a /microwalk directory
          script-directory: ${{ env.script_directory }}
      
      - name: Upload analysis result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/${{ env.script_directory }}/results/report.sarif
          checkout_path: ${{ github.workspace }}
      
      - name: Archive analysis artifacts
        uses: actions/upload-artifact@v3
        with:
          name: leakage-analysis-results
          path: ${{ github.workspace }}/${{ env.script_directory }}/results

